const fs = require ('fs-extra')
fs.emptyDirSync ('folder_01')
fs.ensureFileSync ('folder_01/file_01.txt')
fs.emptyDirSync ('folder_02')
fs.moveSync('folder_01/file_01.txt','folder_02/file_01.txt')
fs.emptyDirSync ('folder_03')
fs.copyFileSync('folder_02/file_01.txt','folder_03/file_01.txt')
fs.removeSync ('folder_02/file_01.txt')
fs.removeSync ('folder_03/file_01.txt')
fs.removeSync('folder_01')
fs.removeSync('folder_02')
fs.removeSync ('folder_03')
